// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmgeWgckb8KYPaNY43KQVgAz5sMahnNs',
    appId: '1:210487830499:web:22c968f57e56f5506662d6',
    messagingSenderId: '210487830499',
    projectId: 'toptop-a2a2c',
    authDomain: 'toptop-a2a2c.firebaseapp.com',
    storageBucket: 'toptop-a2a2c.appspot.com',
    measurementId: 'G-PCK9PPQ8BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm3OSfIbnAsfzjrOThTRovpe86toI6TBs',
    appId: '1:210487830499:android:6ebb5f88806976de6662d6',
    messagingSenderId: '210487830499',
    projectId: 'toptop-a2a2c',
    storageBucket: 'toptop-a2a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPcqi9N1h8J11OtCTsKUFweFkkB9T9iME',
    appId: '1:210487830499:ios:ce5c50ee615d5c3b6662d6',
    messagingSenderId: '210487830499',
    projectId: 'toptop-a2a2c',
    storageBucket: 'toptop-a2a2c.appspot.com',
    iosClientId: '210487830499-hfm8gb68kevng9p4ac3c7ua7t8a6g3fp.apps.googleusercontent.com',
    iosBundleId: 'studio.giangbb.toptop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPcqi9N1h8J11OtCTsKUFweFkkB9T9iME',
    appId: '1:210487830499:ios:ce5c50ee615d5c3b6662d6',
    messagingSenderId: '210487830499',
    projectId: 'toptop-a2a2c',
    storageBucket: 'toptop-a2a2c.appspot.com',
    iosClientId: '210487830499-hfm8gb68kevng9p4ac3c7ua7t8a6g3fp.apps.googleusercontent.com',
    iosBundleId: 'studio.giangbb.toptop',
  );
}
